In [1]:
import numpy as np
from skimage import morphology, measure, util
from scipy import ndimage
from PIL import Image
Image.MAX_IMAGE_PIXELS = None

### Get boundary

In [2]:
arr = np.array([[0, 0, 0, 0, 0],
                [0, 1, 1, 1, 0],
                [0, 1, 1, 1, 0],
                [2, 2, 2, 2, 2],
                [2, 2, 2, 2, 2],
                [2, 2, 2, 2, 2]], dtype='uint8')
arr

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]], dtype=uint8)

In [19]:
arr1 = (arr == 1)

arr1 ^= ndimage.binary_erosion(arr1, morphology.square(width=3))
arr1

array([[False, False, False, False, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [20]:
arr2 = (arr == 2)

arr2 ^= ndimage.binary_erosion(arr2, morphology.square(width=3))
arr2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

### area_opening() and area_closing()

In [78]:
arr = np.array([[0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [2, 2, 1, 2, 2],
                [2, 2, 1, 2, 2],
                [2, 2, 2, 2, 2]], dtype='uint8')

In [79]:
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 2, 1, 2, 2],
       [2, 2, 1, 2, 2],
       [2, 2, 2, 2, 2]], dtype=uint8)

In [97]:
arr2 = arr.copy()
arr2[arr==1] = 2
arr2[arr==2] = 1
arr2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 2, 1, 1],
       [1, 1, 2, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [103]:
arr1 = (arr == 1)
arr[arr == 2] = 1
arr[arr1] = 2
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 2, 1, 1],
       [1, 1, 2, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [90]:
arr2 = util.invert(arr)
arr2

array([[255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [253, 253, 254, 253, 253],
       [253, 253, 254, 253, 253],
       [253, 253, 253, 253, 253]], dtype=uint8)

In [96]:
util.invert(arr_closed)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 2, 1, 2, 2],
       [2, 2, 1, 2, 2],
       [2, 2, 2, 2, 2]], dtype=uint8)

In [91]:
arr3 = util.invert(arr2)
arr3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 2, 1, 2, 2],
       [2, 2, 1, 2, 2],
       [2, 2, 2, 2, 2]], dtype=uint8)

In [85]:
parent, tree_traverser = morphology.max_tree(arr, connectivity=1)
parent, tree_traverser

(array([[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [27, 27,  0, 27, 27],
        [27, 27, 17, 27, 27],
        [27, 27, 17, 27, 27]]),
 array([ 0, 13, 12, 11, 10,  9,  8, 14,  6,  5,  4,  3,  2,  1,  7, 17, 22,
        27, 26, 25, 24, 23, 18, 20, 19, 16, 15, 28, 21, 29]))

In [99]:
arr_opened = morphology.area_opening(arr, area_threshold=3, connectivity=1)
arr_opened

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 2, 1, 2, 2],
       [2, 2, 1, 2, 2],
       [2, 2, 2, 2, 2]], dtype=uint8)

In [57]:
arr_opened_closed = morphology.area_closing(arr_opened, area_threshold=4, connectivity=2)
arr_opened_closed

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 2, 1, 2, 2],
       [2, 2, 1, 2, 2],
       [2, 2, 2, 2, 2]], dtype=uint8)

In [95]:
arr_closed = morphology.area_closing(arr, area_threshold=4, connectivity=2)
arr_closed

array([[255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [253, 253, 254, 253, 253],
       [253, 253, 254, 253, 253],
       [253, 253, 253, 253, 253]], dtype=uint8)

In [59]:
arr_closed_opened = morphology.area_opening(arr_closed, area_threshold=4, connectivity=2)
arr_closed_opened

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 2, 1, 2, 2],
       [2, 2, 1, 2, 2],
       [2, 2, 2, 2, 2]], dtype=uint8)

### Benchmark Time

In [2]:
arr = np.random.randint(0, 255, (10000,10000), dtype='uint8')

In [ ]:
timeit -r1 morphology.diameter_opening(arr, 10)

In [ ]:
timeit -r1 morphology.area_opening(arr, 79)

In [ ]:
# 10x10 arr: area is faster
# 100x100 arr: area is faster
# 1000x1000 arr: area is faster

### PIL Resizing

In [2]:
arr = np.random.randint(0, 255, (60000,70000), dtype='uint8')
arr.shape[0], arr.shape[1]

(60000, 70000)

In [15]:
timeit -r2 np.array(Image.fromarray(np.array(Image.fromarray(arr).resize((arr.shape[0] // 4, arr.shape[1] // 4)))).resize((arr.shape[0], arr.shape[1])))

35.1 s ± 304 ms per loop (mean ± std. dev. of 2 runs, 1 loop each)


In [4]:
img = Image.fromarray(arr, mode='P').resize((arr.shape[0] // 4, arr.shape[1] // 4))
img.width, img.height

(15000, 17500)

In [17]:
factor = 4
200000 // factor**2

12500